server.servlet.session.timeout: 60m

spring:
  application.name: backend
  jpa:
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties.hibernate:
      format_sql: true
      lazy_load_no_trans: true
    open-in-view: false

  servlet.multipart:
    max-file-size: 10240MB
    max-request-size: 10240MB

